### ISSUE TITLE
Demographic Breakdown

### ISSUE THREAD

**Issue by NiluK** [peterhurford/ga_sen_runoff_polling#1]
Hi, what are the crosstabs of this survey? It didn't say at all

Thanks

**Comment by peterhurford** [comment]
Hi @NiluK - I added preliminary crosstabs at https://github.com/peterhurford/ga_sen_runoff_polling/blob/master/GA%20Senate%20Runoff%20-%20Crosstabs.ipynb - I'll add them to the report ASAP

**Comment by NiluK** [comment]
Cheers @peterhurford,

White, not Hispanic    68.113879
Black, non-Hispanic    21.637011
Other                   8.469751
Hispanic                1.779359

This seems extremely high for white % and extremely low for black % considering it was 29% black in the general election.

**Comment by peterhurford** [comment]
Those are the raw unweighted demographics - we apply census weighting to the results to give us a final result of 32.5% Black

**Comment by NiluK** [comment]
Ah that makes sense.

Also why does Warnock and Ossoff win if you use 2016 weighting but Perdue and Loeffler win if you use 2020 weighting?

Hillary lost Georgia by 4 and Biden won Georgia by 0.1 so this is a weird weighting.

**Comment by peterhurford** [comment]
It's because our raw poll data has too many Trump->Biden voters and weighing by 2016 doesn't correct for this. If you don't weigh by 2020 vote also, the poll assumes a ton of conservatives will vote for the Ds. This was the same issue with 2020 general election polling and I guess is caused by people affected by COVID being more likely to be a Trump->Biden voter and more likely to answer a survey.

**Comment by NiluK** [comment]
Are you sure those are Trump->Biden voters and not just Non-voter-> Biden voters

## vote2016 ##

Hillary Clinton    41.637011
Donald Trump       40.996441
Did not vote       12.740214
Other               4.626335
Name: vote2016, dtype: float64

## vote2020 ##

Joe Biden       55.587189
Donald Trump    40.498221
Other            2.206406
Did not vote     1.708185

Trump's percentage didn't change here but non voters decreased a lot.

I agree that the raw vote is underestimating Trump's voters though, BIden didn't get 55% in the general election.

**Comment by peterhurford** [comment]
Yeah, good catch - you're right that the core issue is actually 2016
nonvoters. These people wouldn't get 2016 weights so their liberal skew (in
sampling but not reality) goes uncorrected.

I think the 2016 weights would be better if you applied the same 2016
Trump-Clinton adjustment to 2016 nonvoters as well. But this is basically
what the 2020 weight does.

**Comment by NiluK** [comment]
Okay I think I found out what's the major issue here 

You have Hispanics weighed at 9.897053% by the census for some reason.

When they are only 3-4% of the voting population in Georgia.

https://www.foxnews.com/elections/2020/general-results/voter-analysis?race=S&state=GA

Most Hispanics are immigrants that are not yet eligible to vote due to citizenship status so census and voting history don't work

You also have Perdue winning the Hispanic  58-36 vote in Georgia when Ossoff won the Hispanic vote 58-38. (but keep this as it is)

While  I'm sure some Hispanics might flip to Perdue, I don't think a 20 point shift in 2 months is feasible, do you?

What does the polling look like if you weigh the vote according to the Demographics of the 2020 election?

**Comment by peterhurford** [comment]
@NiluK If you use our current (Census) weights, you get Ossoff -3.9 and Warnock -4.0.

We can look at the demographics of people who say they already voted compared to the actual data. With our current weights, we get:

White 50.2% (according to our poll) / 55.6% (according to actual data)
Black 35.3% / 31.1%
Hispanic 9.5% / 2.2%
Other 4.9% / 11.2%

so I agree we're overweighing hispanics.

But if we use the Fox News data for weights, our toplines are Ossoff -4.0 and Warnock -3.7... not all that different, especially given our margin of error is +/-4.

Here's how that matches with the "already voted" early vote:

White 59.9% / 55.6%
Black 32.6% / 31.1%
Hispanic 2.9% / 2.2%
Other 4.6% / 11.2%

...So a better match to the "already voted" early vote, but the toplines are pretty much unchanged.

**Comment by peterhurford** [comment]
I think we will work to update https://www.openmodelproject.org/inhouse/ to allow people to flip to using the Fox News weights.

**Comment by NiluK** [comment]
Yeah I don't dispute your toplines, just was wondering the weighing of certain demographics which seemed too far from the massive Fox News / AP exit poll.

**Comment by peterhurford** [comment]
Yeah you're definitely right on that! Thanks for the tip.

**Comment by NiluK** [comment]
Btw do you have preferences on who the Libertarian candidate voters are voting for?

**Comment by peterhurford** [comment]
@NiluK I only have that for 2016 Gary Johnson voters... I don't have it for Shane Hazel or Jo Jorgensen unfortunately
